/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applic_data_analysis;

import RequeteReponsePIDEP.ReponsePIDEP;
import RequeteReponsePIDEP.RequetePIDEP;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Julien
 */
public class GetStatDescrContForm extends javax.swing.JDialog
{
    private Socket CSocket;
    private DefaultListModel dlm;
    private DefaultComboBoxModel dcbm;
    /**
     * Creates new form GetStatDescrContForm
     */
    public GetStatDescrContForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Statistiques descriptives");
    }
    
    public GetStatDescrContForm(java.awt.Frame parent, boolean modal, Socket CSocket)
    {
        super(parent, modal);
        initComponents();
        this.CSocket = CSocket;
        dlm = new DefaultListModel();
        lstMode.setModel(dlm);
        this.setTitle("Statistiques descriptives");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnneeChoisie = new javax.swing.JLabel();
        cbxAnnee = new javax.swing.JComboBox();
        lblNombreContainers = new javax.swing.JLabel();
        tfdNombreContainers = new javax.swing.JTextField();
        lblTypeMouvements = new javax.swing.JLabel();
        cbxTypeMouvements = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMode = new javax.swing.JList();
        tfdMoyenne = new javax.swing.JTextField();
        tfdMediane = new javax.swing.JTextField();
        tfdEcartType = new javax.swing.JTextField();
        btnCalculer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAnneeChoisie.setText("Année choisie : ");

        cbxAnnee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNombreContainers.setText("Nombre de containers : ");

        lblTypeMouvements.setText("Type de mouvements :");

        cbxTypeMouvements.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IN", "OUT" }));

        jLabel4.setText("Moyenne : ");

        jLabel5.setText("Médiane : ");

        jLabel6.setText("Ecart-type : ");

        jLabel7.setText("Mode");

        lstMode.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstMode);

        tfdMoyenne.setEnabled(false);

        tfdMediane.setEnabled(false);

        tfdEcartType.setEnabled(false);

        btnCalculer.setText("Calculer les statistiques");
        btnCalculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnneeChoisie)
                            .addComponent(lblNombreContainers)
                            .addComponent(lblTypeMouvements))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTypeMouvements, 0, 74, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfdNombreContainers)
                                .addComponent(cbxAnnee, 0, 74, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tfdMoyenne))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdEcartType))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22)
                        .addComponent(tfdMediane))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCalculer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnneeChoisie)
                    .addComponent(cbxAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreContainers)
                    .addComponent(tfdNombreContainers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeMouvements)
                    .addComponent(cbxTypeMouvements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfdMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdMediane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfdEcartType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculerActionPerformed
        if(!tfdNombreContainers.getText().isEmpty())
        {
            dlm.clear();
            String strRequete = tfdNombreContainers.getText() + "#" + (String)cbxTypeMouvements.getSelectedItem() + "#" + (String)cbxAnnee.getSelectedItem();
            
            try 
            {
                ObjectOutputStream oos = new ObjectOutputStream(CSocket.getOutputStream());
                RequetePIDEP req = new RequetePIDEP(RequetePIDEP.REQUEST_GET_STAT_DESCR_CONT, strRequete);
                oos.writeObject(req);
                oos.flush();
                
                ObjectInputStream ois = new ObjectInputStream(CSocket.getInputStream());
                ReponsePIDEP rep = (ReponsePIDEP)ois.readObject();

                if(rep.getCode() == ReponsePIDEP.REPONSE_OK)
                {
                    String strReponse = (String)rep.getResult();
                    String[] arrayReponse = strReponse.split("#");
                    tfdMoyenne.setText(arrayReponse[0]);
                    tfdMediane.setText(arrayReponse[1]);
                    tfdEcartType.setText(arrayReponse[2]);
                    String[] arrayMode = arrayReponse[3].split("_");
                    
                    for(int i = 0; i < arrayMode.length; i++)
                        dlm.addElement(arrayMode[i]);
                }
                else
                {
                    tfdMoyenne.setText("");
                    tfdMediane.setText("");
                    tfdEcartType.setText("");
                    JOptionPane.showMessageDialog(this, (String)rep.getResult());
                }
            }
            catch (IOException ex)
            {
                Logger.getLogger(GetStatDescrContForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (ClassNotFoundException ex)
            {
                Logger.getLogger(GetStatDescrContForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCalculerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetStatDescrContForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetStatDescrContForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetStatDescrContForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetStatDescrContForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GetStatDescrContForm dialog = new GetStatDescrContForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculer;
    private javax.swing.JComboBox cbxAnnee;
    private javax.swing.JComboBox cbxTypeMouvements;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAnneeChoisie;
    private javax.swing.JLabel lblNombreContainers;
    private javax.swing.JLabel lblTypeMouvements;
    private javax.swing.JList lstMode;
    private javax.swing.JTextField tfdEcartType;
    private javax.swing.JTextField tfdMediane;
    private javax.swing.JTextField tfdMoyenne;
    private javax.swing.JTextField tfdNombreContainers;
    // End of variables declaration//GEN-END:variables

    public void setComboBoxModelAnnee(DefaultComboBoxModel dcbm) {
        cbxAnnee.setModel(dcbm);
    }

}
