/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applic_data_analysis;

import RequeteReponsePIDEP.ReponsePIDEP;
import RequeteReponsePIDEP.RequetePIDEP;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Julien
 */
public class HomogeneityForm extends javax.swing.JDialog 
{
    private Socket CSocket;
    /**
     * Creates new form HomogeneityForm
     */
    public HomogeneityForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Inférence statistiques : test d'homogénéité");
    }
    
    public HomogeneityForm(java.awt.Frame parent, boolean modal, Socket CSocket)
    {
        super(parent, modal);
        initComponents();
        this.CSocket = CSocket;
        this.setTitle("Inférence statistiques : test d'homogénéité");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnLancerTestHomogeneite = new javax.swing.JButton();
        lblResultTest = new javax.swing.JLabel();
        lblChoixDestinations = new javax.swing.JLabel();
        cbxDestination1 = new javax.swing.JComboBox();
        cbxDestination2 = new javax.swing.JComboBox();
        lblNombreContainers = new javax.swing.JLabel();
        tfdNombreContainers = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfdValeurP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDecision = new javax.swing.JLabel();
        tfdDecision = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnLancerTestHomogeneite.setText("Lancer le test d'homogénéité");
        btnLancerTestHomogeneite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancerTestHomogeneiteActionPerformed(evt);
            }
        });

        lblResultTest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultTest.setText("Résultat du test d'homogénéité");

        lblChoixDestinations.setText("Choisissez les 2 destinations du test d'homogénéité");

        cbxDestination1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxDestination2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNombreContainers.setText("Entrez le nombre de containers : ");

        jLabel2.setText("Valeur-p : ");

        tfdValeurP.setEnabled(false);

        jLabel3.setText("Hypothèse nulle : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setText("Le temps de stationnement moyen d'un container pour une destination A est le même que pour une destination B");

        lblDecision.setText("Décisions : ");

        tfdDecision.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLancerTestHomogeneite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(lblResultTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbxDestination2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdValeurP))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDecision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdDecision))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxDestination1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChoixDestinations)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreContainers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfdNombreContainers, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreContainers)
                    .addComponent(tfdNombreContainers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChoixDestinations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDestination1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDestination2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLancerTestHomogeneite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultTest)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdValeurP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDecision)
                    .addComponent(tfdDecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLancerTestHomogeneiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancerTestHomogeneiteActionPerformed
        String strDestination1 = (String)cbxDestination1.getSelectedItem();
        String strDestination2 = (String)cbxDestination2.getSelectedItem();
        
        if(!strDestination1.equals(strDestination2))
        {
            if(!tfdNombreContainers.getText().isEmpty())
            {
                if(Integer.valueOf(tfdNombreContainers.getText()) > 2)
                {
                    try
                    {
                        String strRequete = strDestination1 + "#" + strDestination2 + "#" + tfdNombreContainers.getText();
                        ObjectOutputStream oos = new ObjectOutputStream(CSocket.getOutputStream());
                        RequetePIDEP req = new RequetePIDEP(RequetePIDEP.REQUEST_GET_STAT_INFER_TEST_HOMOG, strRequete);
                        oos.writeObject(req);
                        oos.flush();

                        ObjectInputStream ois = new ObjectInputStream(CSocket.getInputStream());
                        ReponsePIDEP rep = (ReponsePIDEP)ois.readObject();

                        if(rep.getCode() == ReponsePIDEP.REPONSE_OK)
                        {
                            String strReponse = (String)rep.getResult();
                            String[] arrayReponse = strReponse.split("#");
                            tfdValeurP.setText(arrayReponse[0]);
                            tfdDecision.setText(arrayReponse[1]);
                        }
                        else
                            JOptionPane.showMessageDialog(this, (String)rep.getResult());
                    }
                    catch (IOException ex)
                    {
                        Logger.getLogger(GetStatDescrContForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    catch (ClassNotFoundException ex)
                    {
                        Logger.getLogger(GetStatDescrContForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                    JOptionPane.showMessageDialog(this, "2 containers minimum sont requis pour ce test.", "Erreur lors de la saisie du nombre de containers", JOptionPane.ERROR_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this, "Le nombre de containers est obligatoire.", "Pas de nombre de containers", JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Les destinations doivent être différentes.", "Erreur lors du choix des destinations", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnLancerTestHomogeneiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomogeneityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomogeneityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomogeneityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomogeneityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomogeneityForm dialog = new HomogeneityForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancerTestHomogeneite;
    private javax.swing.JComboBox cbxDestination1;
    private javax.swing.JComboBox cbxDestination2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblChoixDestinations;
    private javax.swing.JLabel lblDecision;
    private javax.swing.JLabel lblNombreContainers;
    private javax.swing.JLabel lblResultTest;
    private javax.swing.JTextField tfdDecision;
    private javax.swing.JTextField tfdNombreContainers;
    private javax.swing.JTextField tfdValeurP;
    // End of variables declaration//GEN-END:variables

    void setComboBoxDestination1(DefaultComboBoxModel dcbm)
    {
        cbxDestination1.setModel(dcbm);
    }
    
    void setComboBoxDestination2(DefaultComboBoxModel dcbm)
    {
        cbxDestination2.setModel(dcbm);
    }
}
